# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               以後可能是個好網站
tagline:             'Some random tagline'
description:         "Hello, world.  It's uxmie.  I write stuff."
url:                 http://uxmie.github.io/
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]
#highlighter:         pygments

# About/contact
author:
  name:              uxmie
  url:               http://uxmie.github.io/

# Markdown
markdown:            kramdown
kramdown:
  auto_ids:          true

# Custom vars
version:             1.0.0
